mindmap
  root((Investigacion))
    Controladores PID:​
      Definición
      ::icon(fa fa-book)
        Controladores Proporcional + Integral + Derivativo.​
      Uso
        Amplio en sistemas de control industrial 
            temperatura
            nivel
            flujo
            velocidad
            PH
      Técnicas de Sintonización:
        Objetivo
            Ajustar parámetros de control
                Kp
                Ki
                Kd
                etc
            Evitar problemas
                Saturación
                Ruido
                Sobre/sub-amortiguación
        Ejemplos
            Reglas de Zigler-Nichols
            Autotunning
            Fuzzy autotunning
            Cohen-Coon
            IMC
            Skogestad.
      ETL
      Módulo de IA
        Potencial
            Ofrecer soluciones más flexibles y adaptativas.​
            Necesaria para evaluar si puede igualar o superar el rendimiento de los PID tradicionales.​
        Investigación
    Ventajas
      Simplicidad
      Efectividad.
    Limitaciones
      Adaptación
         Dificultad con cambios dinámicos y no lineales.
      Soluciones
         Lazos de control cerrados
         Lazos en cascada
         Lazos feed forward
         sistemas de Control Interno del Modelo IMCs